print("Hello there")
print("Goodbye!")
print("Hello from the other side")
print("Yay")
print("What's up")
print("We are doing branches today!")
print("We are in main!")
print("Authentication for linux completed!")
